name: percon_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # State management
  flutter_bloc: ^9.1.1 # State Management bloc
  provider: ^6.1.5+1  # This is required for bloc provider setup
  equatable: ^2.0.7 # For value equality in bloc states and events
  # Firebase Operations
  google_sign_in: ^6.1.0 # Google Sign-In integration
  cloud_firestore: ^6.0.0 # Firestore database
  firebase_core: ^4.0.0 # Firebase core
  firebase_auth: ^6.0.1 # Firebase authentication
  # Environment
  flutter_dotenv: ^6.0.0 # Environment
  # Cache
  shared_preferences: ^2.5.3 # Shared preferences for user preferences
  # Svg icons
  flutter_svg: ^2.2.1 # SVG support
  # App icon
  flutter_launcher_icons: ^0.14.4 # Icon generator
  # Localization
  easy_localization: ^3.0.8 # Localization package for multiple languages

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/wanderlust_app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/google_icon.svg
    - assets/json/
    - assets/.env
    - assets/translations/