name: percon_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1 # State Management
  provider: ^6.1.5+1  # This is required for bloc provider setup
  equatable: ^2.0.7 # For value equality in bloc states and events

  google_sign_in: ^6.1.0 # Google Sign-In integration
  cloud_firestore: ^6.0.0 # Firestore database
  firebase_core: ^4.0.0 # Firebase core
  firebase_auth: ^6.0.1 # Firebase authentication
  flutter_dotenv: ^6.0.0 # Environment
  shared_preferences: ^2.5.3 # Shared preferences for user preferences
  flutter_svg: ^2.2.1 # SVG support
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/google_icon.svg
    - assets/json/
    - assets/.env